// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationjob"
)

// MediaGenerationJob is the model entity for the MediaGenerationJob schema.
type MediaGenerationJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID string `json:"public_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus *string `json:"upstream_status,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// UpstreamRequestID holds the value of the "upstream_request_id" field.
	UpstreamRequestID *string `json:"upstream_request_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestJSON holds the value of the "request_json" field.
	RequestJSON json.RawMessage `json:"request_json,omitempty"`
	// UpstreamResponseJSON holds the value of the "upstream_response_json" field.
	UpstreamResponseJSON json.RawMessage `json:"upstream_response_json,omitempty"`
	// ResultURL holds the value of the "result_url" field.
	ResultURL *string `json:"result_url,omitempty"`
	// ResultContentType holds the value of the "result_content_type" field.
	ResultContentType *string `json:"result_content_type,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// AudioVoice holds the value of the "audio_voice" field.
	AudioVoice *string `json:"audio_voice,omitempty"`
	// AudioFormat holds the value of the "audio_format" field.
	AudioFormat *string `json:"audio_format,omitempty"`
	// AudioCharacterCount holds the value of the "audio_character_count" field.
	AudioCharacterCount int `json:"audio_character_count,omitempty"`
	// VideoDurationSeconds holds the value of the "video_duration_seconds" field.
	VideoDurationSeconds int `json:"video_duration_seconds,omitempty"`
	// VideoResolution holds the value of the "video_resolution" field.
	VideoResolution *string `json:"video_resolution,omitempty"`
	// VideoRatio holds the value of the "video_ratio" field.
	VideoRatio *string `json:"video_ratio,omitempty"`
	// VideoCount holds the value of the "video_count" field.
	VideoCount int `json:"video_count,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// UsageRecordedAt holds the value of the "usage_recorded_at" field.
	UsageRecordedAt *time.Time `json:"usage_recorded_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaGenerationJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediagenerationjob.FieldRequestJSON, mediagenerationjob.FieldUpstreamResponseJSON:
			values[i] = new([]byte)
		case mediagenerationjob.FieldID, mediagenerationjob.FieldUserID, mediagenerationjob.FieldAPIKeyID, mediagenerationjob.FieldGroupID, mediagenerationjob.FieldAccountID, mediagenerationjob.FieldAudioCharacterCount, mediagenerationjob.FieldVideoDurationSeconds, mediagenerationjob.FieldVideoCount:
			values[i] = new(sql.NullInt64)
		case mediagenerationjob.FieldPublicID, mediagenerationjob.FieldKind, mediagenerationjob.FieldProvider, mediagenerationjob.FieldPlatform, mediagenerationjob.FieldStatus, mediagenerationjob.FieldUpstreamStatus, mediagenerationjob.FieldUpstreamTaskID, mediagenerationjob.FieldUpstreamRequestID, mediagenerationjob.FieldModel, mediagenerationjob.FieldResultURL, mediagenerationjob.FieldResultContentType, mediagenerationjob.FieldAudioVoice, mediagenerationjob.FieldAudioFormat, mediagenerationjob.FieldVideoResolution, mediagenerationjob.FieldVideoRatio, mediagenerationjob.FieldErrorCode, mediagenerationjob.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case mediagenerationjob.FieldCreatedAt, mediagenerationjob.FieldUpdatedAt, mediagenerationjob.FieldExpiresAt, mediagenerationjob.FieldUsageRecordedAt, mediagenerationjob.FieldSubmittedAt, mediagenerationjob.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaGenerationJob fields.
func (_m *MediaGenerationJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediagenerationjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mediagenerationjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediagenerationjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediagenerationjob.FieldPublicID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value.Valid {
				_m.PublicID = value.String
			}
		case mediagenerationjob.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case mediagenerationjob.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case mediagenerationjob.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case mediagenerationjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case mediagenerationjob.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = new(string)
				*_m.UpstreamStatus = value.String
			}
		case mediagenerationjob.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case mediagenerationjob.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = new(string)
				*_m.UpstreamRequestID = value.String
			}
		case mediagenerationjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case mediagenerationjob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case mediagenerationjob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case mediagenerationjob.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case mediagenerationjob.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case mediagenerationjob.FieldRequestJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestJSON); err != nil {
					return fmt.Errorf("unmarshal field request_json: %w", err)
				}
			}
		case mediagenerationjob.FieldUpstreamResponseJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamResponseJSON); err != nil {
					return fmt.Errorf("unmarshal field upstream_response_json: %w", err)
				}
			}
		case mediagenerationjob.FieldResultURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_url", values[i])
			} else if value.Valid {
				_m.ResultURL = new(string)
				*_m.ResultURL = value.String
			}
		case mediagenerationjob.FieldResultContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_content_type", values[i])
			} else if value.Valid {
				_m.ResultContentType = new(string)
				*_m.ResultContentType = value.String
			}
		case mediagenerationjob.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case mediagenerationjob.FieldAudioVoice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_voice", values[i])
			} else if value.Valid {
				_m.AudioVoice = new(string)
				*_m.AudioVoice = value.String
			}
		case mediagenerationjob.FieldAudioFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_format", values[i])
			} else if value.Valid {
				_m.AudioFormat = new(string)
				*_m.AudioFormat = value.String
			}
		case mediagenerationjob.FieldAudioCharacterCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field audio_character_count", values[i])
			} else if value.Valid {
				_m.AudioCharacterCount = int(value.Int64)
			}
		case mediagenerationjob.FieldVideoDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_duration_seconds", values[i])
			} else if value.Valid {
				_m.VideoDurationSeconds = int(value.Int64)
			}
		case mediagenerationjob.FieldVideoResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_resolution", values[i])
			} else if value.Valid {
				_m.VideoResolution = new(string)
				*_m.VideoResolution = value.String
			}
		case mediagenerationjob.FieldVideoRatio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_ratio", values[i])
			} else if value.Valid {
				_m.VideoRatio = new(string)
				*_m.VideoRatio = value.String
			}
		case mediagenerationjob.FieldVideoCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_count", values[i])
			} else if value.Valid {
				_m.VideoCount = int(value.Int64)
			}
		case mediagenerationjob.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case mediagenerationjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case mediagenerationjob.FieldUsageRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usage_recorded_at", values[i])
			} else if value.Valid {
				_m.UsageRecordedAt = new(time.Time)
				*_m.UsageRecordedAt = value.Time
			}
		case mediagenerationjob.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case mediagenerationjob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaGenerationJob.
// This includes values selected through modifiers, order, etc.
func (_m *MediaGenerationJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MediaGenerationJob.
// Note that you need to call MediaGenerationJob.Unwrap() before calling this method if this MediaGenerationJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaGenerationJob) Update() *MediaGenerationJobUpdateOne {
	return NewMediaGenerationJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaGenerationJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaGenerationJob) Unwrap() *MediaGenerationJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaGenerationJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaGenerationJob) String() string {
	var builder strings.Builder
	builder.WriteString("MediaGenerationJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(_m.PublicID)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.UpstreamStatus; v != nil {
		builder.WriteString("upstream_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamRequestID; v != nil {
		builder.WriteString("upstream_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("request_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestJSON))
	builder.WriteString(", ")
	builder.WriteString("upstream_response_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamResponseJSON))
	builder.WriteString(", ")
	if v := _m.ResultURL; v != nil {
		builder.WriteString("result_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultContentType; v != nil {
		builder.WriteString("result_content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AudioVoice; v != nil {
		builder.WriteString("audio_voice=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AudioFormat; v != nil {
		builder.WriteString("audio_format=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("audio_character_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AudioCharacterCount))
	builder.WriteString(", ")
	builder.WriteString("video_duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoDurationSeconds))
	builder.WriteString(", ")
	if v := _m.VideoResolution; v != nil {
		builder.WriteString("video_resolution=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.VideoRatio; v != nil {
		builder.WriteString("video_ratio=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("video_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoCount))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UsageRecordedAt; v != nil {
		builder.WriteString("usage_recorded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaGenerationJobs is a parsable slice of MediaGenerationJob.
type MediaGenerationJobs []*MediaGenerationJob
