// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationjob"
)

// MediaGenerationJobCreate is the builder for creating a MediaGenerationJob entity.
type MediaGenerationJobCreate struct {
	config
	mutation *MediaGenerationJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaGenerationJobCreate) SetCreatedAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableCreatedAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaGenerationJobCreate) SetUpdatedAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableUpdatedAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *MediaGenerationJobCreate) SetPublicID(v string) *MediaGenerationJobCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *MediaGenerationJobCreate) SetKind(v string) *MediaGenerationJobCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *MediaGenerationJobCreate) SetProvider(v string) *MediaGenerationJobCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *MediaGenerationJobCreate) SetPlatform(v string) *MediaGenerationJobCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MediaGenerationJobCreate) SetStatus(v string) *MediaGenerationJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_c *MediaGenerationJobCreate) SetUpstreamStatus(v string) *MediaGenerationJobCreate {
	_c.mutation.SetUpstreamStatus(v)
	return _c
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableUpstreamStatus(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetUpstreamStatus(*v)
	}
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *MediaGenerationJobCreate) SetUpstreamTaskID(v string) *MediaGenerationJobCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableUpstreamTaskID(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetUpstreamTaskID(*v)
	}
	return _c
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_c *MediaGenerationJobCreate) SetUpstreamRequestID(v string) *MediaGenerationJobCreate {
	_c.mutation.SetUpstreamRequestID(v)
	return _c
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableUpstreamRequestID(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetUpstreamRequestID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MediaGenerationJobCreate) SetUserID(v int64) *MediaGenerationJobCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *MediaGenerationJobCreate) SetAPIKeyID(v int64) *MediaGenerationJobCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *MediaGenerationJobCreate) SetGroupID(v int64) *MediaGenerationJobCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableGroupID(v *int64) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *MediaGenerationJobCreate) SetAccountID(v int64) *MediaGenerationJobCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *MediaGenerationJobCreate) SetModel(v string) *MediaGenerationJobCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRequestJSON sets the "request_json" field.
func (_c *MediaGenerationJobCreate) SetRequestJSON(v json.RawMessage) *MediaGenerationJobCreate {
	_c.mutation.SetRequestJSON(v)
	return _c
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_c *MediaGenerationJobCreate) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobCreate {
	_c.mutation.SetUpstreamResponseJSON(v)
	return _c
}

// SetResultURL sets the "result_url" field.
func (_c *MediaGenerationJobCreate) SetResultURL(v string) *MediaGenerationJobCreate {
	_c.mutation.SetResultURL(v)
	return _c
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableResultURL(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetResultURL(*v)
	}
	return _c
}

// SetResultContentType sets the "result_content_type" field.
func (_c *MediaGenerationJobCreate) SetResultContentType(v string) *MediaGenerationJobCreate {
	_c.mutation.SetResultContentType(v)
	return _c
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableResultContentType(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetResultContentType(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MediaGenerationJobCreate) SetExpiresAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableExpiresAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetAudioVoice sets the "audio_voice" field.
func (_c *MediaGenerationJobCreate) SetAudioVoice(v string) *MediaGenerationJobCreate {
	_c.mutation.SetAudioVoice(v)
	return _c
}

// SetNillableAudioVoice sets the "audio_voice" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableAudioVoice(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetAudioVoice(*v)
	}
	return _c
}

// SetAudioFormat sets the "audio_format" field.
func (_c *MediaGenerationJobCreate) SetAudioFormat(v string) *MediaGenerationJobCreate {
	_c.mutation.SetAudioFormat(v)
	return _c
}

// SetNillableAudioFormat sets the "audio_format" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableAudioFormat(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetAudioFormat(*v)
	}
	return _c
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (_c *MediaGenerationJobCreate) SetAudioCharacterCount(v int) *MediaGenerationJobCreate {
	_c.mutation.SetAudioCharacterCount(v)
	return _c
}

// SetNillableAudioCharacterCount sets the "audio_character_count" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableAudioCharacterCount(v *int) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetAudioCharacterCount(*v)
	}
	return _c
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_c *MediaGenerationJobCreate) SetVideoDurationSeconds(v int) *MediaGenerationJobCreate {
	_c.mutation.SetVideoDurationSeconds(v)
	return _c
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableVideoDurationSeconds(v *int) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetVideoDurationSeconds(*v)
	}
	return _c
}

// SetVideoResolution sets the "video_resolution" field.
func (_c *MediaGenerationJobCreate) SetVideoResolution(v string) *MediaGenerationJobCreate {
	_c.mutation.SetVideoResolution(v)
	return _c
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableVideoResolution(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetVideoResolution(*v)
	}
	return _c
}

// SetVideoRatio sets the "video_ratio" field.
func (_c *MediaGenerationJobCreate) SetVideoRatio(v string) *MediaGenerationJobCreate {
	_c.mutation.SetVideoRatio(v)
	return _c
}

// SetNillableVideoRatio sets the "video_ratio" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableVideoRatio(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetVideoRatio(*v)
	}
	return _c
}

// SetVideoCount sets the "video_count" field.
func (_c *MediaGenerationJobCreate) SetVideoCount(v int) *MediaGenerationJobCreate {
	_c.mutation.SetVideoCount(v)
	return _c
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableVideoCount(v *int) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetVideoCount(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *MediaGenerationJobCreate) SetErrorCode(v string) *MediaGenerationJobCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableErrorCode(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *MediaGenerationJobCreate) SetErrorMessage(v string) *MediaGenerationJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableErrorMessage(v *string) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (_c *MediaGenerationJobCreate) SetUsageRecordedAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetUsageRecordedAt(v)
	return _c
}

// SetNillableUsageRecordedAt sets the "usage_recorded_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableUsageRecordedAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetUsageRecordedAt(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *MediaGenerationJobCreate) SetSubmittedAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableSubmittedAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *MediaGenerationJobCreate) SetCompletedAt(v time.Time) *MediaGenerationJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *MediaGenerationJobCreate) SetNillableCompletedAt(v *time.Time) *MediaGenerationJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the MediaGenerationJobMutation object of the builder.
func (_c *MediaGenerationJobCreate) Mutation() *MediaGenerationJobMutation {
	return _c.mutation
}

// Save creates the MediaGenerationJob in the database.
func (_c *MediaGenerationJobCreate) Save(ctx context.Context) (*MediaGenerationJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaGenerationJobCreate) SaveX(ctx context.Context) *MediaGenerationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaGenerationJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaGenerationJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaGenerationJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediagenerationjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediagenerationjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AudioCharacterCount(); !ok {
		v := mediagenerationjob.DefaultAudioCharacterCount
		_c.mutation.SetAudioCharacterCount(v)
	}
	if _, ok := _c.mutation.VideoDurationSeconds(); !ok {
		v := mediagenerationjob.DefaultVideoDurationSeconds
		_c.mutation.SetVideoDurationSeconds(v)
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		v := mediagenerationjob.DefaultVideoCount
		_c.mutation.SetVideoCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaGenerationJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaGenerationJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MediaGenerationJob.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "MediaGenerationJob.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := mediagenerationjob.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "MediaGenerationJob.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := mediagenerationjob.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "MediaGenerationJob.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := mediagenerationjob.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "MediaGenerationJob.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := mediagenerationjob.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MediaGenerationJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mediagenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamStatus(); ok {
		if err := mediagenerationjob.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := mediagenerationjob.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamRequestID(); ok {
		if err := mediagenerationjob.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MediaGenerationJob.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "MediaGenerationJob.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "MediaGenerationJob.account_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "MediaGenerationJob.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := mediagenerationjob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResultContentType(); ok {
		if err := mediagenerationjob.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.result_content_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AudioVoice(); ok {
		if err := mediagenerationjob.AudioVoiceValidator(v); err != nil {
			return &ValidationError{Name: "audio_voice", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_voice": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AudioFormat(); ok {
		if err := mediagenerationjob.AudioFormatValidator(v); err != nil {
			return &ValidationError{Name: "audio_format", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AudioCharacterCount(); !ok {
		return &ValidationError{Name: "audio_character_count", err: errors.New(`ent: missing required field "MediaGenerationJob.audio_character_count"`)}
	}
	if _, ok := _c.mutation.VideoDurationSeconds(); !ok {
		return &ValidationError{Name: "video_duration_seconds", err: errors.New(`ent: missing required field "MediaGenerationJob.video_duration_seconds"`)}
	}
	if v, ok := _c.mutation.VideoResolution(); ok {
		if err := mediagenerationjob.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_resolution": %w`, err)}
		}
	}
	if v, ok := _c.mutation.VideoRatio(); ok {
		if err := mediagenerationjob.VideoRatioValidator(v); err != nil {
			return &ValidationError{Name: "video_ratio", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		return &ValidationError{Name: "video_count", err: errors.New(`ent: missing required field "MediaGenerationJob.video_count"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := mediagenerationjob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.error_code": %w`, err)}
		}
	}
	return nil
}

func (_c *MediaGenerationJobCreate) sqlSave(ctx context.Context) (*MediaGenerationJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaGenerationJobCreate) createSpec() (*MediaGenerationJob, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaGenerationJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediagenerationjob.Table, sqlgraph.NewFieldSpec(mediagenerationjob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(mediagenerationjob.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(mediagenerationjob.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(mediagenerationjob.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(mediagenerationjob.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mediagenerationjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UpstreamStatus(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamStatus, field.TypeString, value)
		_node.UpstreamStatus = &value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = &value
	}
	if value, ok := _c.mutation.UpstreamRequestID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamRequestID, field.TypeString, value)
		_node.UpstreamRequestID = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(mediagenerationjob.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(mediagenerationjob.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(mediagenerationjob.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(mediagenerationjob.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(mediagenerationjob.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldRequestJSON, field.TypeJSON, value)
		_node.RequestJSON = value
	}
	if value, ok := _c.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamResponseJSON, field.TypeJSON, value)
		_node.UpstreamResponseJSON = value
	}
	if value, ok := _c.mutation.ResultURL(); ok {
		_spec.SetField(mediagenerationjob.FieldResultURL, field.TypeString, value)
		_node.ResultURL = &value
	}
	if value, ok := _c.mutation.ResultContentType(); ok {
		_spec.SetField(mediagenerationjob.FieldResultContentType, field.TypeString, value)
		_node.ResultContentType = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(mediagenerationjob.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.AudioVoice(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioVoice, field.TypeString, value)
		_node.AudioVoice = &value
	}
	if value, ok := _c.mutation.AudioFormat(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioFormat, field.TypeString, value)
		_node.AudioFormat = &value
	}
	if value, ok := _c.mutation.AudioCharacterCount(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioCharacterCount, field.TypeInt, value)
		_node.AudioCharacterCount = value
	}
	if value, ok := _c.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoDurationSeconds, field.TypeInt, value)
		_node.VideoDurationSeconds = value
	}
	if value, ok := _c.mutation.VideoResolution(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoResolution, field.TypeString, value)
		_node.VideoResolution = &value
	}
	if value, ok := _c.mutation.VideoRatio(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoRatio, field.TypeString, value)
		_node.VideoRatio = &value
	}
	if value, ok := _c.mutation.VideoCount(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoCount, field.TypeInt, value)
		_node.VideoCount = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.UsageRecordedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUsageRecordedAt, field.TypeTime, value)
		_node.UsageRecordedAt = &value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaGenerationJob.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaGenerationJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaGenerationJobCreate) OnConflict(opts ...sql.ConflictOption) *MediaGenerationJobUpsertOne {
	_c.conflict = opts
	return &MediaGenerationJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaGenerationJobCreate) OnConflictColumns(columns ...string) *MediaGenerationJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaGenerationJobUpsertOne{
		create: _c,
	}
}

type (
	// MediaGenerationJobUpsertOne is the builder for "upsert"-ing
	//  one MediaGenerationJob node.
	MediaGenerationJobUpsertOne struct {
		create *MediaGenerationJobCreate
	}

	// MediaGenerationJobUpsert is the "OnConflict" setter.
	MediaGenerationJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaGenerationJobUpsert) SetUpdatedAt(v time.Time) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUpdatedAt() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUpdatedAt)
	return u
}

// SetPublicID sets the "public_id" field.
func (u *MediaGenerationJobUpsert) SetPublicID(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldPublicID, v)
	return u
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdatePublicID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldPublicID)
	return u
}

// SetKind sets the "kind" field.
func (u *MediaGenerationJobUpsert) SetKind(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateKind() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldKind)
	return u
}

// SetProvider sets the "provider" field.
func (u *MediaGenerationJobUpsert) SetProvider(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateProvider() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldProvider)
	return u
}

// SetPlatform sets the "platform" field.
func (u *MediaGenerationJobUpsert) SetPlatform(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdatePlatform() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldPlatform)
	return u
}

// SetStatus sets the "status" field.
func (u *MediaGenerationJobUpsert) SetStatus(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateStatus() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldStatus)
	return u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *MediaGenerationJobUpsert) SetUpstreamStatus(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUpstreamStatus, v)
	return u
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUpstreamStatus() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUpstreamStatus)
	return u
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (u *MediaGenerationJobUpsert) ClearUpstreamStatus() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldUpstreamStatus)
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaGenerationJobUpsert) SetUpstreamTaskID(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUpstreamTaskID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUpstreamTaskID)
	return u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaGenerationJobUpsert) ClearUpstreamTaskID() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldUpstreamTaskID)
	return u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *MediaGenerationJobUpsert) SetUpstreamRequestID(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUpstreamRequestID, v)
	return u
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUpstreamRequestID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUpstreamRequestID)
	return u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *MediaGenerationJobUpsert) ClearUpstreamRequestID() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldUpstreamRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *MediaGenerationJobUpsert) SetUserID(v int64) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUserID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *MediaGenerationJobUpsert) AddUserID(v int64) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaGenerationJobUpsert) SetAPIKeyID(v int64) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateAPIKeyID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaGenerationJobUpsert) AddAPIKeyID(v int64) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldAPIKeyID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *MediaGenerationJobUpsert) SetGroupID(v int64) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateGroupID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *MediaGenerationJobUpsert) AddGroupID(v int64) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MediaGenerationJobUpsert) ClearGroupID() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *MediaGenerationJobUpsert) SetAccountID(v int64) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateAccountID() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaGenerationJobUpsert) AddAccountID(v int64) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldAccountID, v)
	return u
}

// SetModel sets the "model" field.
func (u *MediaGenerationJobUpsert) SetModel(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateModel() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldModel)
	return u
}

// SetRequestJSON sets the "request_json" field.
func (u *MediaGenerationJobUpsert) SetRequestJSON(v json.RawMessage) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldRequestJSON, v)
	return u
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateRequestJSON() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldRequestJSON)
	return u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *MediaGenerationJobUpsert) ClearRequestJSON() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldRequestJSON)
	return u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *MediaGenerationJobUpsert) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUpstreamResponseJSON, v)
	return u
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUpstreamResponseJSON() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUpstreamResponseJSON)
	return u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *MediaGenerationJobUpsert) ClearUpstreamResponseJSON() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldUpstreamResponseJSON)
	return u
}

// SetResultURL sets the "result_url" field.
func (u *MediaGenerationJobUpsert) SetResultURL(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldResultURL, v)
	return u
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateResultURL() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldResultURL)
	return u
}

// ClearResultURL clears the value of the "result_url" field.
func (u *MediaGenerationJobUpsert) ClearResultURL() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldResultURL)
	return u
}

// SetResultContentType sets the "result_content_type" field.
func (u *MediaGenerationJobUpsert) SetResultContentType(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldResultContentType, v)
	return u
}

// UpdateResultContentType sets the "result_content_type" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateResultContentType() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldResultContentType)
	return u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (u *MediaGenerationJobUpsert) ClearResultContentType() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldResultContentType)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *MediaGenerationJobUpsert) SetExpiresAt(v time.Time) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateExpiresAt() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MediaGenerationJobUpsert) ClearExpiresAt() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldExpiresAt)
	return u
}

// SetAudioVoice sets the "audio_voice" field.
func (u *MediaGenerationJobUpsert) SetAudioVoice(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldAudioVoice, v)
	return u
}

// UpdateAudioVoice sets the "audio_voice" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateAudioVoice() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldAudioVoice)
	return u
}

// ClearAudioVoice clears the value of the "audio_voice" field.
func (u *MediaGenerationJobUpsert) ClearAudioVoice() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldAudioVoice)
	return u
}

// SetAudioFormat sets the "audio_format" field.
func (u *MediaGenerationJobUpsert) SetAudioFormat(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldAudioFormat, v)
	return u
}

// UpdateAudioFormat sets the "audio_format" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateAudioFormat() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldAudioFormat)
	return u
}

// ClearAudioFormat clears the value of the "audio_format" field.
func (u *MediaGenerationJobUpsert) ClearAudioFormat() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldAudioFormat)
	return u
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (u *MediaGenerationJobUpsert) SetAudioCharacterCount(v int) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldAudioCharacterCount, v)
	return u
}

// UpdateAudioCharacterCount sets the "audio_character_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateAudioCharacterCount() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldAudioCharacterCount)
	return u
}

// AddAudioCharacterCount adds v to the "audio_character_count" field.
func (u *MediaGenerationJobUpsert) AddAudioCharacterCount(v int) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldAudioCharacterCount, v)
	return u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsert) SetVideoDurationSeconds(v int) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldVideoDurationSeconds, v)
	return u
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateVideoDurationSeconds() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldVideoDurationSeconds)
	return u
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsert) AddVideoDurationSeconds(v int) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldVideoDurationSeconds, v)
	return u
}

// SetVideoResolution sets the "video_resolution" field.
func (u *MediaGenerationJobUpsert) SetVideoResolution(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldVideoResolution, v)
	return u
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateVideoResolution() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldVideoResolution)
	return u
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *MediaGenerationJobUpsert) ClearVideoResolution() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldVideoResolution)
	return u
}

// SetVideoRatio sets the "video_ratio" field.
func (u *MediaGenerationJobUpsert) SetVideoRatio(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldVideoRatio, v)
	return u
}

// UpdateVideoRatio sets the "video_ratio" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateVideoRatio() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldVideoRatio)
	return u
}

// ClearVideoRatio clears the value of the "video_ratio" field.
func (u *MediaGenerationJobUpsert) ClearVideoRatio() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldVideoRatio)
	return u
}

// SetVideoCount sets the "video_count" field.
func (u *MediaGenerationJobUpsert) SetVideoCount(v int) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldVideoCount, v)
	return u
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateVideoCount() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldVideoCount)
	return u
}

// AddVideoCount adds v to the "video_count" field.
func (u *MediaGenerationJobUpsert) AddVideoCount(v int) *MediaGenerationJobUpsert {
	u.Add(mediagenerationjob.FieldVideoCount, v)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *MediaGenerationJobUpsert) SetErrorCode(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateErrorCode() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *MediaGenerationJobUpsert) ClearErrorCode() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaGenerationJobUpsert) SetErrorMessage(v string) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateErrorMessage() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaGenerationJobUpsert) ClearErrorMessage() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldErrorMessage)
	return u
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsert) SetUsageRecordedAt(v time.Time) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldUsageRecordedAt, v)
	return u
}

// UpdateUsageRecordedAt sets the "usage_recorded_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateUsageRecordedAt() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldUsageRecordedAt)
	return u
}

// ClearUsageRecordedAt clears the value of the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsert) ClearUsageRecordedAt() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldUsageRecordedAt)
	return u
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *MediaGenerationJobUpsert) SetSubmittedAt(v time.Time) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldSubmittedAt, v)
	return u
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateSubmittedAt() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldSubmittedAt)
	return u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *MediaGenerationJobUpsert) ClearSubmittedAt() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldSubmittedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *MediaGenerationJobUpsert) SetCompletedAt(v time.Time) *MediaGenerationJobUpsert {
	u.Set(mediagenerationjob.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsert) UpdateCompletedAt() *MediaGenerationJobUpsert {
	u.SetExcluded(mediagenerationjob.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MediaGenerationJobUpsert) ClearCompletedAt() *MediaGenerationJobUpsert {
	u.SetNull(mediagenerationjob.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaGenerationJobUpsertOne) UpdateNewValues() *MediaGenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mediagenerationjob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaGenerationJobUpsertOne) Ignore() *MediaGenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaGenerationJobUpsertOne) DoNothing() *MediaGenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaGenerationJobCreate.OnConflict
// documentation for more info.
func (u *MediaGenerationJobUpsertOne) Update(set func(*MediaGenerationJobUpsert)) *MediaGenerationJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaGenerationJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaGenerationJobUpsertOne) SetUpdatedAt(v time.Time) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUpdatedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *MediaGenerationJobUpsertOne) SetPublicID(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdatePublicID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdatePublicID()
	})
}

// SetKind sets the "kind" field.
func (u *MediaGenerationJobUpsertOne) SetKind(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateKind() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateKind()
	})
}

// SetProvider sets the "provider" field.
func (u *MediaGenerationJobUpsertOne) SetProvider(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateProvider() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateProvider()
	})
}

// SetPlatform sets the "platform" field.
func (u *MediaGenerationJobUpsertOne) SetPlatform(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdatePlatform() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdatePlatform()
	})
}

// SetStatus sets the "status" field.
func (u *MediaGenerationJobUpsertOne) SetStatus(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateStatus() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *MediaGenerationJobUpsertOne) SetUpstreamStatus(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUpstreamStatus() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (u *MediaGenerationJobUpsertOne) ClearUpstreamStatus() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamStatus()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaGenerationJobUpsertOne) SetUpstreamTaskID(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUpstreamTaskID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaGenerationJobUpsertOne) ClearUpstreamTaskID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *MediaGenerationJobUpsertOne) SetUpstreamRequestID(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUpstreamRequestID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *MediaGenerationJobUpsertOne) ClearUpstreamRequestID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *MediaGenerationJobUpsertOne) SetUserID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MediaGenerationJobUpsertOne) AddUserID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUserID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaGenerationJobUpsertOne) SetAPIKeyID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaGenerationJobUpsertOne) AddAPIKeyID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateAPIKeyID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MediaGenerationJobUpsertOne) SetGroupID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MediaGenerationJobUpsertOne) AddGroupID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateGroupID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MediaGenerationJobUpsertOne) ClearGroupID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *MediaGenerationJobUpsertOne) SetAccountID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaGenerationJobUpsertOne) AddAccountID(v int64) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateAccountID() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAccountID()
	})
}

// SetModel sets the "model" field.
func (u *MediaGenerationJobUpsertOne) SetModel(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateModel() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateModel()
	})
}

// SetRequestJSON sets the "request_json" field.
func (u *MediaGenerationJobUpsertOne) SetRequestJSON(v json.RawMessage) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetRequestJSON(v)
	})
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateRequestJSON() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateRequestJSON()
	})
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *MediaGenerationJobUpsertOne) ClearRequestJSON() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearRequestJSON()
	})
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *MediaGenerationJobUpsertOne) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamResponseJSON(v)
	})
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUpstreamResponseJSON() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamResponseJSON()
	})
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *MediaGenerationJobUpsertOne) ClearUpstreamResponseJSON() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamResponseJSON()
	})
}

// SetResultURL sets the "result_url" field.
func (u *MediaGenerationJobUpsertOne) SetResultURL(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateResultURL() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *MediaGenerationJobUpsertOne) ClearResultURL() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearResultURL()
	})
}

// SetResultContentType sets the "result_content_type" field.
func (u *MediaGenerationJobUpsertOne) SetResultContentType(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetResultContentType(v)
	})
}

// UpdateResultContentType sets the "result_content_type" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateResultContentType() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateResultContentType()
	})
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (u *MediaGenerationJobUpsertOne) ClearResultContentType() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearResultContentType()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MediaGenerationJobUpsertOne) SetExpiresAt(v time.Time) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateExpiresAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MediaGenerationJobUpsertOne) ClearExpiresAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearExpiresAt()
	})
}

// SetAudioVoice sets the "audio_voice" field.
func (u *MediaGenerationJobUpsertOne) SetAudioVoice(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioVoice(v)
	})
}

// UpdateAudioVoice sets the "audio_voice" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateAudioVoice() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioVoice()
	})
}

// ClearAudioVoice clears the value of the "audio_voice" field.
func (u *MediaGenerationJobUpsertOne) ClearAudioVoice() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearAudioVoice()
	})
}

// SetAudioFormat sets the "audio_format" field.
func (u *MediaGenerationJobUpsertOne) SetAudioFormat(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioFormat(v)
	})
}

// UpdateAudioFormat sets the "audio_format" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateAudioFormat() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioFormat()
	})
}

// ClearAudioFormat clears the value of the "audio_format" field.
func (u *MediaGenerationJobUpsertOne) ClearAudioFormat() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearAudioFormat()
	})
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (u *MediaGenerationJobUpsertOne) SetAudioCharacterCount(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioCharacterCount(v)
	})
}

// AddAudioCharacterCount adds v to the "audio_character_count" field.
func (u *MediaGenerationJobUpsertOne) AddAudioCharacterCount(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAudioCharacterCount(v)
	})
}

// UpdateAudioCharacterCount sets the "audio_character_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateAudioCharacterCount() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioCharacterCount()
	})
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsertOne) SetVideoDurationSeconds(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoDurationSeconds(v)
	})
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsertOne) AddVideoDurationSeconds(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddVideoDurationSeconds(v)
	})
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateVideoDurationSeconds() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoDurationSeconds()
	})
}

// SetVideoResolution sets the "video_resolution" field.
func (u *MediaGenerationJobUpsertOne) SetVideoResolution(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoResolution(v)
	})
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateVideoResolution() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoResolution()
	})
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *MediaGenerationJobUpsertOne) ClearVideoResolution() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearVideoResolution()
	})
}

// SetVideoRatio sets the "video_ratio" field.
func (u *MediaGenerationJobUpsertOne) SetVideoRatio(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoRatio(v)
	})
}

// UpdateVideoRatio sets the "video_ratio" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateVideoRatio() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoRatio()
	})
}

// ClearVideoRatio clears the value of the "video_ratio" field.
func (u *MediaGenerationJobUpsertOne) ClearVideoRatio() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearVideoRatio()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *MediaGenerationJobUpsertOne) SetVideoCount(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *MediaGenerationJobUpsertOne) AddVideoCount(v int) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateVideoCount() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoCount()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *MediaGenerationJobUpsertOne) SetErrorCode(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateErrorCode() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *MediaGenerationJobUpsertOne) ClearErrorCode() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaGenerationJobUpsertOne) SetErrorMessage(v string) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateErrorMessage() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaGenerationJobUpsertOne) ClearErrorMessage() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsertOne) SetUsageRecordedAt(v time.Time) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUsageRecordedAt(v)
	})
}

// UpdateUsageRecordedAt sets the "usage_recorded_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateUsageRecordedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUsageRecordedAt()
	})
}

// ClearUsageRecordedAt clears the value of the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsertOne) ClearUsageRecordedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUsageRecordedAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *MediaGenerationJobUpsertOne) SetSubmittedAt(v time.Time) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateSubmittedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *MediaGenerationJobUpsertOne) ClearSubmittedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *MediaGenerationJobUpsertOne) SetCompletedAt(v time.Time) *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertOne) UpdateCompletedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MediaGenerationJobUpsertOne) ClearCompletedAt() *MediaGenerationJobUpsertOne {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *MediaGenerationJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaGenerationJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaGenerationJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaGenerationJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaGenerationJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaGenerationJobCreateBulk is the builder for creating many MediaGenerationJob entities in bulk.
type MediaGenerationJobCreateBulk struct {
	config
	err      error
	builders []*MediaGenerationJobCreate
	conflict []sql.ConflictOption
}

// Save creates the MediaGenerationJob entities in the database.
func (_c *MediaGenerationJobCreateBulk) Save(ctx context.Context) ([]*MediaGenerationJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaGenerationJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaGenerationJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaGenerationJobCreateBulk) SaveX(ctx context.Context) []*MediaGenerationJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaGenerationJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaGenerationJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MediaGenerationJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaGenerationJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaGenerationJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaGenerationJobUpsertBulk {
	_c.conflict = opts
	return &MediaGenerationJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaGenerationJobCreateBulk) OnConflictColumns(columns ...string) *MediaGenerationJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaGenerationJobUpsertBulk{
		create: _c,
	}
}

// MediaGenerationJobUpsertBulk is the builder for "upsert"-ing
// a bulk of MediaGenerationJob nodes.
type MediaGenerationJobUpsertBulk struct {
	create *MediaGenerationJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MediaGenerationJobUpsertBulk) UpdateNewValues() *MediaGenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mediagenerationjob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MediaGenerationJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaGenerationJobUpsertBulk) Ignore() *MediaGenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaGenerationJobUpsertBulk) DoNothing() *MediaGenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaGenerationJobCreateBulk.OnConflict
// documentation for more info.
func (u *MediaGenerationJobUpsertBulk) Update(set func(*MediaGenerationJobUpsert)) *MediaGenerationJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaGenerationJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaGenerationJobUpsertBulk) SetUpdatedAt(v time.Time) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUpdatedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *MediaGenerationJobUpsertBulk) SetPublicID(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdatePublicID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdatePublicID()
	})
}

// SetKind sets the "kind" field.
func (u *MediaGenerationJobUpsertBulk) SetKind(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateKind() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateKind()
	})
}

// SetProvider sets the "provider" field.
func (u *MediaGenerationJobUpsertBulk) SetProvider(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateProvider() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateProvider()
	})
}

// SetPlatform sets the "platform" field.
func (u *MediaGenerationJobUpsertBulk) SetPlatform(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdatePlatform() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdatePlatform()
	})
}

// SetStatus sets the "status" field.
func (u *MediaGenerationJobUpsertBulk) SetStatus(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateStatus() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamStatus sets the "upstream_status" field.
func (u *MediaGenerationJobUpsertBulk) SetUpstreamStatus(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamStatus(v)
	})
}

// UpdateUpstreamStatus sets the "upstream_status" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUpstreamStatus() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamStatus()
	})
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (u *MediaGenerationJobUpsertBulk) ClearUpstreamStatus() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamStatus()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *MediaGenerationJobUpsertBulk) SetUpstreamTaskID(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUpstreamTaskID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *MediaGenerationJobUpsertBulk) ClearUpstreamTaskID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (u *MediaGenerationJobUpsertBulk) SetUpstreamRequestID(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamRequestID(v)
	})
}

// UpdateUpstreamRequestID sets the "upstream_request_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUpstreamRequestID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamRequestID()
	})
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (u *MediaGenerationJobUpsertBulk) ClearUpstreamRequestID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *MediaGenerationJobUpsertBulk) SetUserID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *MediaGenerationJobUpsertBulk) AddUserID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUserID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *MediaGenerationJobUpsertBulk) SetAPIKeyID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *MediaGenerationJobUpsertBulk) AddAPIKeyID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateAPIKeyID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MediaGenerationJobUpsertBulk) SetGroupID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *MediaGenerationJobUpsertBulk) AddGroupID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateGroupID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *MediaGenerationJobUpsertBulk) ClearGroupID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *MediaGenerationJobUpsertBulk) SetAccountID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *MediaGenerationJobUpsertBulk) AddAccountID(v int64) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateAccountID() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAccountID()
	})
}

// SetModel sets the "model" field.
func (u *MediaGenerationJobUpsertBulk) SetModel(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateModel() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateModel()
	})
}

// SetRequestJSON sets the "request_json" field.
func (u *MediaGenerationJobUpsertBulk) SetRequestJSON(v json.RawMessage) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetRequestJSON(v)
	})
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateRequestJSON() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateRequestJSON()
	})
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *MediaGenerationJobUpsertBulk) ClearRequestJSON() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearRequestJSON()
	})
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *MediaGenerationJobUpsertBulk) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUpstreamResponseJSON(v)
	})
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUpstreamResponseJSON() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUpstreamResponseJSON()
	})
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *MediaGenerationJobUpsertBulk) ClearUpstreamResponseJSON() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUpstreamResponseJSON()
	})
}

// SetResultURL sets the "result_url" field.
func (u *MediaGenerationJobUpsertBulk) SetResultURL(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetResultURL(v)
	})
}

// UpdateResultURL sets the "result_url" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateResultURL() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateResultURL()
	})
}

// ClearResultURL clears the value of the "result_url" field.
func (u *MediaGenerationJobUpsertBulk) ClearResultURL() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearResultURL()
	})
}

// SetResultContentType sets the "result_content_type" field.
func (u *MediaGenerationJobUpsertBulk) SetResultContentType(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetResultContentType(v)
	})
}

// UpdateResultContentType sets the "result_content_type" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateResultContentType() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateResultContentType()
	})
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (u *MediaGenerationJobUpsertBulk) ClearResultContentType() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearResultContentType()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MediaGenerationJobUpsertBulk) SetExpiresAt(v time.Time) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateExpiresAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MediaGenerationJobUpsertBulk) ClearExpiresAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearExpiresAt()
	})
}

// SetAudioVoice sets the "audio_voice" field.
func (u *MediaGenerationJobUpsertBulk) SetAudioVoice(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioVoice(v)
	})
}

// UpdateAudioVoice sets the "audio_voice" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateAudioVoice() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioVoice()
	})
}

// ClearAudioVoice clears the value of the "audio_voice" field.
func (u *MediaGenerationJobUpsertBulk) ClearAudioVoice() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearAudioVoice()
	})
}

// SetAudioFormat sets the "audio_format" field.
func (u *MediaGenerationJobUpsertBulk) SetAudioFormat(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioFormat(v)
	})
}

// UpdateAudioFormat sets the "audio_format" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateAudioFormat() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioFormat()
	})
}

// ClearAudioFormat clears the value of the "audio_format" field.
func (u *MediaGenerationJobUpsertBulk) ClearAudioFormat() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearAudioFormat()
	})
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (u *MediaGenerationJobUpsertBulk) SetAudioCharacterCount(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetAudioCharacterCount(v)
	})
}

// AddAudioCharacterCount adds v to the "audio_character_count" field.
func (u *MediaGenerationJobUpsertBulk) AddAudioCharacterCount(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddAudioCharacterCount(v)
	})
}

// UpdateAudioCharacterCount sets the "audio_character_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateAudioCharacterCount() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateAudioCharacterCount()
	})
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsertBulk) SetVideoDurationSeconds(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoDurationSeconds(v)
	})
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *MediaGenerationJobUpsertBulk) AddVideoDurationSeconds(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddVideoDurationSeconds(v)
	})
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateVideoDurationSeconds() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoDurationSeconds()
	})
}

// SetVideoResolution sets the "video_resolution" field.
func (u *MediaGenerationJobUpsertBulk) SetVideoResolution(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoResolution(v)
	})
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateVideoResolution() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoResolution()
	})
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *MediaGenerationJobUpsertBulk) ClearVideoResolution() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearVideoResolution()
	})
}

// SetVideoRatio sets the "video_ratio" field.
func (u *MediaGenerationJobUpsertBulk) SetVideoRatio(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoRatio(v)
	})
}

// UpdateVideoRatio sets the "video_ratio" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateVideoRatio() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoRatio()
	})
}

// ClearVideoRatio clears the value of the "video_ratio" field.
func (u *MediaGenerationJobUpsertBulk) ClearVideoRatio() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearVideoRatio()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *MediaGenerationJobUpsertBulk) SetVideoCount(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *MediaGenerationJobUpsertBulk) AddVideoCount(v int) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateVideoCount() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateVideoCount()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *MediaGenerationJobUpsertBulk) SetErrorCode(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateErrorCode() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *MediaGenerationJobUpsertBulk) ClearErrorCode() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *MediaGenerationJobUpsertBulk) SetErrorMessage(v string) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateErrorMessage() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *MediaGenerationJobUpsertBulk) ClearErrorMessage() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsertBulk) SetUsageRecordedAt(v time.Time) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetUsageRecordedAt(v)
	})
}

// UpdateUsageRecordedAt sets the "usage_recorded_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateUsageRecordedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateUsageRecordedAt()
	})
}

// ClearUsageRecordedAt clears the value of the "usage_recorded_at" field.
func (u *MediaGenerationJobUpsertBulk) ClearUsageRecordedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearUsageRecordedAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *MediaGenerationJobUpsertBulk) SetSubmittedAt(v time.Time) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateSubmittedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *MediaGenerationJobUpsertBulk) ClearSubmittedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *MediaGenerationJobUpsertBulk) SetCompletedAt(v time.Time) *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MediaGenerationJobUpsertBulk) UpdateCompletedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MediaGenerationJobUpsertBulk) ClearCompletedAt() *MediaGenerationJobUpsertBulk {
	return u.Update(func(s *MediaGenerationJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *MediaGenerationJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MediaGenerationJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaGenerationJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaGenerationJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
