// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaGenerationJobUpdate is the builder for updating MediaGenerationJob entities.
type MediaGenerationJobUpdate struct {
	config
	hooks    []Hook
	mutation *MediaGenerationJobMutation
}

// Where appends a list predicates to the MediaGenerationJobUpdate builder.
func (_u *MediaGenerationJobUpdate) Where(ps ...predicate.MediaGenerationJob) *MediaGenerationJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaGenerationJobUpdate) SetUpdatedAt(v time.Time) *MediaGenerationJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *MediaGenerationJobUpdate) SetPublicID(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillablePublicID(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *MediaGenerationJobUpdate) SetKind(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableKind(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *MediaGenerationJobUpdate) SetProvider(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableProvider(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *MediaGenerationJobUpdate) SetPlatform(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillablePlatform(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaGenerationJobUpdate) SetStatus(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableStatus(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *MediaGenerationJobUpdate) SetUpstreamStatus(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableUpstreamStatus(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (_u *MediaGenerationJobUpdate) ClearUpstreamStatus() *MediaGenerationJobUpdate {
	_u.mutation.ClearUpstreamStatus()
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaGenerationJobUpdate) SetUpstreamTaskID(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableUpstreamTaskID(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaGenerationJobUpdate) ClearUpstreamTaskID() *MediaGenerationJobUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *MediaGenerationJobUpdate) SetUpstreamRequestID(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableUpstreamRequestID(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *MediaGenerationJobUpdate) ClearUpstreamRequestID() *MediaGenerationJobUpdate {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaGenerationJobUpdate) SetUserID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableUserID(v *int64) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaGenerationJobUpdate) AddUserID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaGenerationJobUpdate) SetAPIKeyID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableAPIKeyID(v *int64) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaGenerationJobUpdate) AddAPIKeyID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MediaGenerationJobUpdate) SetGroupID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableGroupID(v *int64) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MediaGenerationJobUpdate) AddGroupID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MediaGenerationJobUpdate) ClearGroupID() *MediaGenerationJobUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaGenerationJobUpdate) SetAccountID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableAccountID(v *int64) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaGenerationJobUpdate) AddAccountID(v int64) *MediaGenerationJobUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *MediaGenerationJobUpdate) SetModel(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableModel(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestJSON sets the "request_json" field.
func (_u *MediaGenerationJobUpdate) SetRequestJSON(v json.RawMessage) *MediaGenerationJobUpdate {
	_u.mutation.SetRequestJSON(v)
	return _u
}

// AppendRequestJSON appends value to the "request_json" field.
func (_u *MediaGenerationJobUpdate) AppendRequestJSON(v json.RawMessage) *MediaGenerationJobUpdate {
	_u.mutation.AppendRequestJSON(v)
	return _u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (_u *MediaGenerationJobUpdate) ClearRequestJSON() *MediaGenerationJobUpdate {
	_u.mutation.ClearRequestJSON()
	return _u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdate) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpdate {
	_u.mutation.SetUpstreamResponseJSON(v)
	return _u
}

// AppendUpstreamResponseJSON appends value to the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdate) AppendUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpdate {
	_u.mutation.AppendUpstreamResponseJSON(v)
	return _u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdate) ClearUpstreamResponseJSON() *MediaGenerationJobUpdate {
	_u.mutation.ClearUpstreamResponseJSON()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *MediaGenerationJobUpdate) SetResultURL(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableResultURL(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *MediaGenerationJobUpdate) ClearResultURL() *MediaGenerationJobUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *MediaGenerationJobUpdate) SetResultContentType(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableResultContentType(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *MediaGenerationJobUpdate) ClearResultContentType() *MediaGenerationJobUpdate {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MediaGenerationJobUpdate) SetExpiresAt(v time.Time) *MediaGenerationJobUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableExpiresAt(v *time.Time) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MediaGenerationJobUpdate) ClearExpiresAt() *MediaGenerationJobUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetAudioVoice sets the "audio_voice" field.
func (_u *MediaGenerationJobUpdate) SetAudioVoice(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetAudioVoice(v)
	return _u
}

// SetNillableAudioVoice sets the "audio_voice" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableAudioVoice(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetAudioVoice(*v)
	}
	return _u
}

// ClearAudioVoice clears the value of the "audio_voice" field.
func (_u *MediaGenerationJobUpdate) ClearAudioVoice() *MediaGenerationJobUpdate {
	_u.mutation.ClearAudioVoice()
	return _u
}

// SetAudioFormat sets the "audio_format" field.
func (_u *MediaGenerationJobUpdate) SetAudioFormat(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetAudioFormat(v)
	return _u
}

// SetNillableAudioFormat sets the "audio_format" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableAudioFormat(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetAudioFormat(*v)
	}
	return _u
}

// ClearAudioFormat clears the value of the "audio_format" field.
func (_u *MediaGenerationJobUpdate) ClearAudioFormat() *MediaGenerationJobUpdate {
	_u.mutation.ClearAudioFormat()
	return _u
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (_u *MediaGenerationJobUpdate) SetAudioCharacterCount(v int) *MediaGenerationJobUpdate {
	_u.mutation.ResetAudioCharacterCount()
	_u.mutation.SetAudioCharacterCount(v)
	return _u
}

// SetNillableAudioCharacterCount sets the "audio_character_count" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableAudioCharacterCount(v *int) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetAudioCharacterCount(*v)
	}
	return _u
}

// AddAudioCharacterCount adds value to the "audio_character_count" field.
func (_u *MediaGenerationJobUpdate) AddAudioCharacterCount(v int) *MediaGenerationJobUpdate {
	_u.mutation.AddAudioCharacterCount(v)
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *MediaGenerationJobUpdate) SetVideoDurationSeconds(v int) *MediaGenerationJobUpdate {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableVideoDurationSeconds(v *int) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *MediaGenerationJobUpdate) AddVideoDurationSeconds(v int) *MediaGenerationJobUpdate {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *MediaGenerationJobUpdate) SetVideoResolution(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableVideoResolution(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (_u *MediaGenerationJobUpdate) ClearVideoResolution() *MediaGenerationJobUpdate {
	_u.mutation.ClearVideoResolution()
	return _u
}

// SetVideoRatio sets the "video_ratio" field.
func (_u *MediaGenerationJobUpdate) SetVideoRatio(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetVideoRatio(v)
	return _u
}

// SetNillableVideoRatio sets the "video_ratio" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableVideoRatio(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetVideoRatio(*v)
	}
	return _u
}

// ClearVideoRatio clears the value of the "video_ratio" field.
func (_u *MediaGenerationJobUpdate) ClearVideoRatio() *MediaGenerationJobUpdate {
	_u.mutation.ClearVideoRatio()
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *MediaGenerationJobUpdate) SetVideoCount(v int) *MediaGenerationJobUpdate {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableVideoCount(v *int) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *MediaGenerationJobUpdate) AddVideoCount(v int) *MediaGenerationJobUpdate {
	_u.mutation.AddVideoCount(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *MediaGenerationJobUpdate) SetErrorCode(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableErrorCode(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *MediaGenerationJobUpdate) ClearErrorCode() *MediaGenerationJobUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaGenerationJobUpdate) SetErrorMessage(v string) *MediaGenerationJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableErrorMessage(v *string) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaGenerationJobUpdate) ClearErrorMessage() *MediaGenerationJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (_u *MediaGenerationJobUpdate) SetUsageRecordedAt(v time.Time) *MediaGenerationJobUpdate {
	_u.mutation.SetUsageRecordedAt(v)
	return _u
}

// SetNillableUsageRecordedAt sets the "usage_recorded_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableUsageRecordedAt(v *time.Time) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetUsageRecordedAt(*v)
	}
	return _u
}

// ClearUsageRecordedAt clears the value of the "usage_recorded_at" field.
func (_u *MediaGenerationJobUpdate) ClearUsageRecordedAt() *MediaGenerationJobUpdate {
	_u.mutation.ClearUsageRecordedAt()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *MediaGenerationJobUpdate) SetSubmittedAt(v time.Time) *MediaGenerationJobUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableSubmittedAt(v *time.Time) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *MediaGenerationJobUpdate) ClearSubmittedAt() *MediaGenerationJobUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *MediaGenerationJobUpdate) SetCompletedAt(v time.Time) *MediaGenerationJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdate) SetNillableCompletedAt(v *time.Time) *MediaGenerationJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *MediaGenerationJobUpdate) ClearCompletedAt() *MediaGenerationJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the MediaGenerationJobMutation object of the builder.
func (_u *MediaGenerationJobUpdate) Mutation() *MediaGenerationJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaGenerationJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaGenerationJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaGenerationJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaGenerationJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaGenerationJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediagenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaGenerationJobUpdate) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := mediagenerationjob.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediagenerationjob.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := mediagenerationjob.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := mediagenerationjob.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediagenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := mediagenerationjob.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediagenerationjob.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := mediagenerationjob.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := mediagenerationjob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := mediagenerationjob.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioVoice(); ok {
		if err := mediagenerationjob.AudioVoiceValidator(v); err != nil {
			return &ValidationError{Name: "audio_voice", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_voice": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioFormat(); ok {
		if err := mediagenerationjob.AudioFormatValidator(v); err != nil {
			return &ValidationError{Name: "audio_format", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoResolution(); ok {
		if err := mediagenerationjob.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoRatio(); ok {
		if err := mediagenerationjob.VideoRatioValidator(v); err != nil {
			return &ValidationError{Name: "video_ratio", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := mediagenerationjob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaGenerationJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediagenerationjob.Table, mediagenerationjob.Columns, sqlgraph.NewFieldSpec(mediagenerationjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(mediagenerationjob.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediagenerationjob.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(mediagenerationjob.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(mediagenerationjob.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediagenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamStatus, field.TypeString, value)
	}
	if _u.mutation.UpstreamStatusCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamStatus, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediagenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediagenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediagenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediagenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mediagenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mediagenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediagenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediagenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(mediagenerationjob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldRequestJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationjob.FieldRequestJSON, value)
		})
	}
	if _u.mutation.RequestJSONCleared() {
		_spec.ClearField(mediagenerationjob.FieldRequestJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamResponseJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamResponseJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationjob.FieldUpstreamResponseJSON, value)
		})
	}
	if _u.mutation.UpstreamResponseJSONCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamResponseJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(mediagenerationjob.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(mediagenerationjob.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(mediagenerationjob.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(mediagenerationjob.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mediagenerationjob.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AudioVoice(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioVoice, field.TypeString, value)
	}
	if _u.mutation.AudioVoiceCleared() {
		_spec.ClearField(mediagenerationjob.FieldAudioVoice, field.TypeString)
	}
	if value, ok := _u.mutation.AudioFormat(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioFormat, field.TypeString, value)
	}
	if _u.mutation.AudioFormatCleared() {
		_spec.ClearField(mediagenerationjob.FieldAudioFormat, field.TypeString)
	}
	if value, ok := _u.mutation.AudioCharacterCount(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAudioCharacterCount(); ok {
		_spec.AddField(mediagenerationjob.FieldAudioCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(mediagenerationjob.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoResolution, field.TypeString, value)
	}
	if _u.mutation.VideoResolutionCleared() {
		_spec.ClearField(mediagenerationjob.FieldVideoResolution, field.TypeString)
	}
	if value, ok := _u.mutation.VideoRatio(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoRatio, field.TypeString, value)
	}
	if _u.mutation.VideoRatioCleared() {
		_spec.ClearField(mediagenerationjob.FieldVideoRatio, field.TypeString)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(mediagenerationjob.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(mediagenerationjob.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediagenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UsageRecordedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUsageRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldUsageRecordedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediagenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaGenerationJobUpdateOne is the builder for updating a single MediaGenerationJob entity.
type MediaGenerationJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaGenerationJobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaGenerationJobUpdateOne) SetUpdatedAt(v time.Time) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *MediaGenerationJobUpdateOne) SetPublicID(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillablePublicID(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *MediaGenerationJobUpdateOne) SetKind(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableKind(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *MediaGenerationJobUpdateOne) SetProvider(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableProvider(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *MediaGenerationJobUpdateOne) SetPlatform(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillablePlatform(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaGenerationJobUpdateOne) SetStatus(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableStatus(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *MediaGenerationJobUpdateOne) SetUpstreamStatus(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableUpstreamStatus(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// ClearUpstreamStatus clears the value of the "upstream_status" field.
func (_u *MediaGenerationJobUpdateOne) ClearUpstreamStatus() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamStatus()
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaGenerationJobUpdateOne) SetUpstreamTaskID(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableUpstreamTaskID(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaGenerationJobUpdateOne) ClearUpstreamTaskID() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *MediaGenerationJobUpdateOne) SetUpstreamRequestID(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableUpstreamRequestID(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *MediaGenerationJobUpdateOne) ClearUpstreamRequestID() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaGenerationJobUpdateOne) SetUserID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableUserID(v *int64) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaGenerationJobUpdateOne) AddUserID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaGenerationJobUpdateOne) SetAPIKeyID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableAPIKeyID(v *int64) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaGenerationJobUpdateOne) AddAPIKeyID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MediaGenerationJobUpdateOne) SetGroupID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableGroupID(v *int64) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MediaGenerationJobUpdateOne) AddGroupID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MediaGenerationJobUpdateOne) ClearGroupID() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaGenerationJobUpdateOne) SetAccountID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableAccountID(v *int64) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaGenerationJobUpdateOne) AddAccountID(v int64) *MediaGenerationJobUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *MediaGenerationJobUpdateOne) SetModel(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableModel(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestJSON sets the "request_json" field.
func (_u *MediaGenerationJobUpdateOne) SetRequestJSON(v json.RawMessage) *MediaGenerationJobUpdateOne {
	_u.mutation.SetRequestJSON(v)
	return _u
}

// AppendRequestJSON appends value to the "request_json" field.
func (_u *MediaGenerationJobUpdateOne) AppendRequestJSON(v json.RawMessage) *MediaGenerationJobUpdateOne {
	_u.mutation.AppendRequestJSON(v)
	return _u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (_u *MediaGenerationJobUpdateOne) ClearRequestJSON() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearRequestJSON()
	return _u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdateOne) SetUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUpstreamResponseJSON(v)
	return _u
}

// AppendUpstreamResponseJSON appends value to the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdateOne) AppendUpstreamResponseJSON(v json.RawMessage) *MediaGenerationJobUpdateOne {
	_u.mutation.AppendUpstreamResponseJSON(v)
	return _u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (_u *MediaGenerationJobUpdateOne) ClearUpstreamResponseJSON() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamResponseJSON()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *MediaGenerationJobUpdateOne) SetResultURL(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableResultURL(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *MediaGenerationJobUpdateOne) ClearResultURL() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultContentType sets the "result_content_type" field.
func (_u *MediaGenerationJobUpdateOne) SetResultContentType(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetResultContentType(v)
	return _u
}

// SetNillableResultContentType sets the "result_content_type" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableResultContentType(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetResultContentType(*v)
	}
	return _u
}

// ClearResultContentType clears the value of the "result_content_type" field.
func (_u *MediaGenerationJobUpdateOne) ClearResultContentType() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearResultContentType()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MediaGenerationJobUpdateOne) SetExpiresAt(v time.Time) *MediaGenerationJobUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableExpiresAt(v *time.Time) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MediaGenerationJobUpdateOne) ClearExpiresAt() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetAudioVoice sets the "audio_voice" field.
func (_u *MediaGenerationJobUpdateOne) SetAudioVoice(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetAudioVoice(v)
	return _u
}

// SetNillableAudioVoice sets the "audio_voice" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableAudioVoice(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetAudioVoice(*v)
	}
	return _u
}

// ClearAudioVoice clears the value of the "audio_voice" field.
func (_u *MediaGenerationJobUpdateOne) ClearAudioVoice() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearAudioVoice()
	return _u
}

// SetAudioFormat sets the "audio_format" field.
func (_u *MediaGenerationJobUpdateOne) SetAudioFormat(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetAudioFormat(v)
	return _u
}

// SetNillableAudioFormat sets the "audio_format" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableAudioFormat(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetAudioFormat(*v)
	}
	return _u
}

// ClearAudioFormat clears the value of the "audio_format" field.
func (_u *MediaGenerationJobUpdateOne) ClearAudioFormat() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearAudioFormat()
	return _u
}

// SetAudioCharacterCount sets the "audio_character_count" field.
func (_u *MediaGenerationJobUpdateOne) SetAudioCharacterCount(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetAudioCharacterCount()
	_u.mutation.SetAudioCharacterCount(v)
	return _u
}

// SetNillableAudioCharacterCount sets the "audio_character_count" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableAudioCharacterCount(v *int) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetAudioCharacterCount(*v)
	}
	return _u
}

// AddAudioCharacterCount adds value to the "audio_character_count" field.
func (_u *MediaGenerationJobUpdateOne) AddAudioCharacterCount(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.AddAudioCharacterCount(v)
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *MediaGenerationJobUpdateOne) SetVideoDurationSeconds(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableVideoDurationSeconds(v *int) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *MediaGenerationJobUpdateOne) AddVideoDurationSeconds(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *MediaGenerationJobUpdateOne) SetVideoResolution(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableVideoResolution(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (_u *MediaGenerationJobUpdateOne) ClearVideoResolution() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearVideoResolution()
	return _u
}

// SetVideoRatio sets the "video_ratio" field.
func (_u *MediaGenerationJobUpdateOne) SetVideoRatio(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetVideoRatio(v)
	return _u
}

// SetNillableVideoRatio sets the "video_ratio" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableVideoRatio(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetVideoRatio(*v)
	}
	return _u
}

// ClearVideoRatio clears the value of the "video_ratio" field.
func (_u *MediaGenerationJobUpdateOne) ClearVideoRatio() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearVideoRatio()
	return _u
}

// SetVideoCount sets the "video_count" field.
func (_u *MediaGenerationJobUpdateOne) SetVideoCount(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.ResetVideoCount()
	_u.mutation.SetVideoCount(v)
	return _u
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableVideoCount(v *int) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetVideoCount(*v)
	}
	return _u
}

// AddVideoCount adds value to the "video_count" field.
func (_u *MediaGenerationJobUpdateOne) AddVideoCount(v int) *MediaGenerationJobUpdateOne {
	_u.mutation.AddVideoCount(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *MediaGenerationJobUpdateOne) SetErrorCode(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableErrorCode(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *MediaGenerationJobUpdateOne) ClearErrorCode() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaGenerationJobUpdateOne) SetErrorMessage(v string) *MediaGenerationJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableErrorMessage(v *string) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaGenerationJobUpdateOne) ClearErrorMessage() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUsageRecordedAt sets the "usage_recorded_at" field.
func (_u *MediaGenerationJobUpdateOne) SetUsageRecordedAt(v time.Time) *MediaGenerationJobUpdateOne {
	_u.mutation.SetUsageRecordedAt(v)
	return _u
}

// SetNillableUsageRecordedAt sets the "usage_recorded_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableUsageRecordedAt(v *time.Time) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetUsageRecordedAt(*v)
	}
	return _u
}

// ClearUsageRecordedAt clears the value of the "usage_recorded_at" field.
func (_u *MediaGenerationJobUpdateOne) ClearUsageRecordedAt() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearUsageRecordedAt()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *MediaGenerationJobUpdateOne) SetSubmittedAt(v time.Time) *MediaGenerationJobUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableSubmittedAt(v *time.Time) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *MediaGenerationJobUpdateOne) ClearSubmittedAt() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *MediaGenerationJobUpdateOne) SetCompletedAt(v time.Time) *MediaGenerationJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *MediaGenerationJobUpdateOne) SetNillableCompletedAt(v *time.Time) *MediaGenerationJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *MediaGenerationJobUpdateOne) ClearCompletedAt() *MediaGenerationJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the MediaGenerationJobMutation object of the builder.
func (_u *MediaGenerationJobUpdateOne) Mutation() *MediaGenerationJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaGenerationJobUpdate builder.
func (_u *MediaGenerationJobUpdateOne) Where(ps ...predicate.MediaGenerationJob) *MediaGenerationJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaGenerationJobUpdateOne) Select(field string, fields ...string) *MediaGenerationJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaGenerationJob entity.
func (_u *MediaGenerationJobUpdateOne) Save(ctx context.Context) (*MediaGenerationJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaGenerationJobUpdateOne) SaveX(ctx context.Context) *MediaGenerationJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaGenerationJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaGenerationJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaGenerationJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediagenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaGenerationJobUpdateOne) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := mediagenerationjob.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := mediagenerationjob.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := mediagenerationjob.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := mediagenerationjob.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediagenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := mediagenerationjob.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediagenerationjob.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := mediagenerationjob.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := mediagenerationjob.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultContentType(); ok {
		if err := mediagenerationjob.ResultContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "result_content_type", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.result_content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioVoice(); ok {
		if err := mediagenerationjob.AudioVoiceValidator(v); err != nil {
			return &ValidationError{Name: "audio_voice", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_voice": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AudioFormat(); ok {
		if err := mediagenerationjob.AudioFormatValidator(v); err != nil {
			return &ValidationError{Name: "audio_format", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.audio_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoResolution(); ok {
		if err := mediagenerationjob.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoRatio(); ok {
		if err := mediagenerationjob.VideoRatioValidator(v); err != nil {
			return &ValidationError{Name: "video_ratio", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.video_ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := mediagenerationjob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationJob.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaGenerationJobUpdateOne) sqlSave(ctx context.Context) (_node *MediaGenerationJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediagenerationjob.Table, mediagenerationjob.Columns, sqlgraph.NewFieldSpec(mediagenerationjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaGenerationJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediagenerationjob.FieldID)
		for _, f := range fields {
			if !mediagenerationjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediagenerationjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(mediagenerationjob.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(mediagenerationjob.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(mediagenerationjob.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(mediagenerationjob.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediagenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamStatus, field.TypeString, value)
	}
	if _u.mutation.UpstreamStatusCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamStatus, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediagenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediagenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediagenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediagenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mediagenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mediagenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mediagenerationjob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediagenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediagenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(mediagenerationjob.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldRequestJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationjob.FieldRequestJSON, value)
		})
	}
	if _u.mutation.RequestJSONCleared() {
		_spec.ClearField(mediagenerationjob.FieldRequestJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(mediagenerationjob.FieldUpstreamResponseJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamResponseJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationjob.FieldUpstreamResponseJSON, value)
		})
	}
	if _u.mutation.UpstreamResponseJSONCleared() {
		_spec.ClearField(mediagenerationjob.FieldUpstreamResponseJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(mediagenerationjob.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(mediagenerationjob.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultContentType(); ok {
		_spec.SetField(mediagenerationjob.FieldResultContentType, field.TypeString, value)
	}
	if _u.mutation.ResultContentTypeCleared() {
		_spec.ClearField(mediagenerationjob.FieldResultContentType, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mediagenerationjob.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AudioVoice(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioVoice, field.TypeString, value)
	}
	if _u.mutation.AudioVoiceCleared() {
		_spec.ClearField(mediagenerationjob.FieldAudioVoice, field.TypeString)
	}
	if value, ok := _u.mutation.AudioFormat(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioFormat, field.TypeString, value)
	}
	if _u.mutation.AudioFormatCleared() {
		_spec.ClearField(mediagenerationjob.FieldAudioFormat, field.TypeString)
	}
	if value, ok := _u.mutation.AudioCharacterCount(); ok {
		_spec.SetField(mediagenerationjob.FieldAudioCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAudioCharacterCount(); ok {
		_spec.AddField(mediagenerationjob.FieldAudioCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(mediagenerationjob.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoResolution, field.TypeString, value)
	}
	if _u.mutation.VideoResolutionCleared() {
		_spec.ClearField(mediagenerationjob.FieldVideoResolution, field.TypeString)
	}
	if value, ok := _u.mutation.VideoRatio(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoRatio, field.TypeString, value)
	}
	if _u.mutation.VideoRatioCleared() {
		_spec.ClearField(mediagenerationjob.FieldVideoRatio, field.TypeString)
	}
	if value, ok := _u.mutation.VideoCount(); ok {
		_spec.SetField(mediagenerationjob.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoCount(); ok {
		_spec.AddField(mediagenerationjob.FieldVideoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(mediagenerationjob.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediagenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediagenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UsageRecordedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldUsageRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldUsageRecordedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(mediagenerationjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(mediagenerationjob.FieldCompletedAt, field.TypeTime)
	}
	_node = &MediaGenerationJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediagenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
