// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaGenerationJobDelete is the builder for deleting a MediaGenerationJob entity.
type MediaGenerationJobDelete struct {
	config
	hooks    []Hook
	mutation *MediaGenerationJobMutation
}

// Where appends a list predicates to the MediaGenerationJobDelete builder.
func (_d *MediaGenerationJobDelete) Where(ps ...predicate.MediaGenerationJob) *MediaGenerationJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaGenerationJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaGenerationJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaGenerationJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediagenerationjob.Table, sqlgraph.NewFieldSpec(mediagenerationjob.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaGenerationJobDeleteOne is the builder for deleting a single MediaGenerationJob entity.
type MediaGenerationJobDeleteOne struct {
	_d *MediaGenerationJobDelete
}

// Where appends a list predicates to the MediaGenerationJobDelete builder.
func (_d *MediaGenerationJobDeleteOne) Where(ps ...predicate.MediaGenerationJob) *MediaGenerationJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaGenerationJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediagenerationjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaGenerationJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
