// Code generated by ent, DO NOT EDIT.

package mediagenerationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mediagenerationjob type in the database.
	Label = "media_generation_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldUpstreamRequestID holds the string denoting the upstream_request_id field in the database.
	FieldUpstreamRequestID = "upstream_request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRequestJSON holds the string denoting the request_json field in the database.
	FieldRequestJSON = "request_json"
	// FieldUpstreamResponseJSON holds the string denoting the upstream_response_json field in the database.
	FieldUpstreamResponseJSON = "upstream_response_json"
	// FieldResultURL holds the string denoting the result_url field in the database.
	FieldResultURL = "result_url"
	// FieldResultContentType holds the string denoting the result_content_type field in the database.
	FieldResultContentType = "result_content_type"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldAudioVoice holds the string denoting the audio_voice field in the database.
	FieldAudioVoice = "audio_voice"
	// FieldAudioFormat holds the string denoting the audio_format field in the database.
	FieldAudioFormat = "audio_format"
	// FieldAudioCharacterCount holds the string denoting the audio_character_count field in the database.
	FieldAudioCharacterCount = "audio_character_count"
	// FieldVideoDurationSeconds holds the string denoting the video_duration_seconds field in the database.
	FieldVideoDurationSeconds = "video_duration_seconds"
	// FieldVideoResolution holds the string denoting the video_resolution field in the database.
	FieldVideoResolution = "video_resolution"
	// FieldVideoRatio holds the string denoting the video_ratio field in the database.
	FieldVideoRatio = "video_ratio"
	// FieldVideoCount holds the string denoting the video_count field in the database.
	FieldVideoCount = "video_count"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldUsageRecordedAt holds the string denoting the usage_recorded_at field in the database.
	FieldUsageRecordedAt = "usage_recorded_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the mediagenerationjob in the database.
	Table = "media_generation_jobs"
)

// Columns holds all SQL columns for mediagenerationjob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublicID,
	FieldKind,
	FieldProvider,
	FieldPlatform,
	FieldStatus,
	FieldUpstreamStatus,
	FieldUpstreamTaskID,
	FieldUpstreamRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldAccountID,
	FieldModel,
	FieldRequestJSON,
	FieldUpstreamResponseJSON,
	FieldResultURL,
	FieldResultContentType,
	FieldExpiresAt,
	FieldAudioVoice,
	FieldAudioFormat,
	FieldAudioCharacterCount,
	FieldVideoDurationSeconds,
	FieldVideoResolution,
	FieldVideoRatio,
	FieldVideoCount,
	FieldErrorCode,
	FieldErrorMessage,
	FieldUsageRecordedAt,
	FieldSubmittedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// UpstreamRequestIDValidator is a validator for the "upstream_request_id" field. It is called by the builders before save.
	UpstreamRequestIDValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// ResultContentTypeValidator is a validator for the "result_content_type" field. It is called by the builders before save.
	ResultContentTypeValidator func(string) error
	// AudioVoiceValidator is a validator for the "audio_voice" field. It is called by the builders before save.
	AudioVoiceValidator func(string) error
	// AudioFormatValidator is a validator for the "audio_format" field. It is called by the builders before save.
	AudioFormatValidator func(string) error
	// DefaultAudioCharacterCount holds the default value on creation for the "audio_character_count" field.
	DefaultAudioCharacterCount int
	// DefaultVideoDurationSeconds holds the default value on creation for the "video_duration_seconds" field.
	DefaultVideoDurationSeconds int
	// VideoResolutionValidator is a validator for the "video_resolution" field. It is called by the builders before save.
	VideoResolutionValidator func(string) error
	// VideoRatioValidator is a validator for the "video_ratio" field. It is called by the builders before save.
	VideoRatioValidator func(string) error
	// DefaultVideoCount holds the default value on creation for the "video_count" field.
	DefaultVideoCount int
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
)

// OrderOption defines the ordering options for the MediaGenerationJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByUpstreamRequestID orders the results by the upstream_request_id field.
func ByUpstreamRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByResultURL orders the results by the result_url field.
func ByResultURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultURL, opts...).ToFunc()
}

// ByResultContentType orders the results by the result_content_type field.
func ByResultContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultContentType, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByAudioVoice orders the results by the audio_voice field.
func ByAudioVoice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioVoice, opts...).ToFunc()
}

// ByAudioFormat orders the results by the audio_format field.
func ByAudioFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioFormat, opts...).ToFunc()
}

// ByAudioCharacterCount orders the results by the audio_character_count field.
func ByAudioCharacterCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioCharacterCount, opts...).ToFunc()
}

// ByVideoDurationSeconds orders the results by the video_duration_seconds field.
func ByVideoDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoDurationSeconds, opts...).ToFunc()
}

// ByVideoResolution orders the results by the video_resolution field.
func ByVideoResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoResolution, opts...).ToFunc()
}

// ByVideoRatio orders the results by the video_ratio field.
func ByVideoRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoRatio, opts...).ToFunc()
}

// ByVideoCount orders the results by the video_count field.
func ByVideoCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoCount, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByUsageRecordedAt orders the results by the usage_recorded_at field.
func ByUsageRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageRecordedAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
