// Code generated by ent, DO NOT EDIT.

package mediagenerationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldPublicID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldKind, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldProvider, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldPlatform, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldStatus, v))
}

// UpstreamStatus applies equality check predicate on the "upstream_status" field. It's identical to UpstreamStatusEQ.
func UpstreamStatus(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamRequestID applies equality check predicate on the "upstream_request_id" field. It's identical to UpstreamRequestIDEQ.
func UpstreamRequestID(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAccountID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldModel, v))
}

// ResultURL applies equality check predicate on the "result_url" field. It's identical to ResultURLEQ.
func ResultURL(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldResultURL, v))
}

// ResultContentType applies equality check predicate on the "result_content_type" field. It's identical to ResultContentTypeEQ.
func ResultContentType(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldResultContentType, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldExpiresAt, v))
}

// AudioVoice applies equality check predicate on the "audio_voice" field. It's identical to AudioVoiceEQ.
func AudioVoice(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioVoice, v))
}

// AudioFormat applies equality check predicate on the "audio_format" field. It's identical to AudioFormatEQ.
func AudioFormat(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioFormat, v))
}

// AudioCharacterCount applies equality check predicate on the "audio_character_count" field. It's identical to AudioCharacterCountEQ.
func AudioCharacterCount(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioCharacterCount, v))
}

// VideoDurationSeconds applies equality check predicate on the "video_duration_seconds" field. It's identical to VideoDurationSecondsEQ.
func VideoDurationSeconds(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoDurationSeconds, v))
}

// VideoResolution applies equality check predicate on the "video_resolution" field. It's identical to VideoResolutionEQ.
func VideoResolution(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoResolution, v))
}

// VideoRatio applies equality check predicate on the "video_ratio" field. It's identical to VideoRatioEQ.
func VideoRatio(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoRatio, v))
}

// VideoCount applies equality check predicate on the "video_count" field. It's identical to VideoCountEQ.
func VideoCount(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoCount, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// UsageRecordedAt applies equality check predicate on the "usage_recorded_at" field. It's identical to UsageRecordedAtEQ.
func UsageRecordedAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUsageRecordedAt, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldPublicID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldKind, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldProvider, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldPlatform, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldStatus, v))
}

// UpstreamStatusEQ applies the EQ predicate on the "upstream_status" field.
func UpstreamStatusEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusNEQ applies the NEQ predicate on the "upstream_status" field.
func UpstreamStatusNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusIn applies the In predicate on the "upstream_status" field.
func UpstreamStatusIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusNotIn applies the NotIn predicate on the "upstream_status" field.
func UpstreamStatusNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusGT applies the GT predicate on the "upstream_status" field.
func UpstreamStatusGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUpstreamStatus, v))
}

// UpstreamStatusGTE applies the GTE predicate on the "upstream_status" field.
func UpstreamStatusGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUpstreamStatus, v))
}

// UpstreamStatusLT applies the LT predicate on the "upstream_status" field.
func UpstreamStatusLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUpstreamStatus, v))
}

// UpstreamStatusLTE applies the LTE predicate on the "upstream_status" field.
func UpstreamStatusLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUpstreamStatus, v))
}

// UpstreamStatusContains applies the Contains predicate on the "upstream_status" field.
func UpstreamStatusContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldUpstreamStatus, v))
}

// UpstreamStatusHasPrefix applies the HasPrefix predicate on the "upstream_status" field.
func UpstreamStatusHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldUpstreamStatus, v))
}

// UpstreamStatusHasSuffix applies the HasSuffix predicate on the "upstream_status" field.
func UpstreamStatusHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldUpstreamStatus, v))
}

// UpstreamStatusIsNil applies the IsNil predicate on the "upstream_status" field.
func UpstreamStatusIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldUpstreamStatus))
}

// UpstreamStatusNotNil applies the NotNil predicate on the "upstream_status" field.
func UpstreamStatusNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldUpstreamStatus))
}

// UpstreamStatusEqualFold applies the EqualFold predicate on the "upstream_status" field.
func UpstreamStatusEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldUpstreamStatus, v))
}

// UpstreamStatusContainsFold applies the ContainsFold predicate on the "upstream_status" field.
func UpstreamStatusContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldUpstreamStatus, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// UpstreamRequestIDEQ applies the EQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDNEQ applies the NEQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIn applies the In predicate on the "upstream_request_id" field.
func UpstreamRequestIDIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDNotIn applies the NotIn predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDGT applies the GT predicate on the "upstream_request_id" field.
func UpstreamRequestIDGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDGTE applies the GTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLT applies the LT predicate on the "upstream_request_id" field.
func UpstreamRequestIDLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLTE applies the LTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContains applies the Contains predicate on the "upstream_request_id" field.
func UpstreamRequestIDContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasPrefix applies the HasPrefix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasSuffix applies the HasSuffix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIsNil applies the IsNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDNotNil applies the NotNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDEqualFold applies the EqualFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContainsFold applies the ContainsFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldUpstreamRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldAccountID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldModel, v))
}

// RequestJSONIsNil applies the IsNil predicate on the "request_json" field.
func RequestJSONIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldRequestJSON))
}

// RequestJSONNotNil applies the NotNil predicate on the "request_json" field.
func RequestJSONNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldRequestJSON))
}

// UpstreamResponseJSONIsNil applies the IsNil predicate on the "upstream_response_json" field.
func UpstreamResponseJSONIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldUpstreamResponseJSON))
}

// UpstreamResponseJSONNotNil applies the NotNil predicate on the "upstream_response_json" field.
func UpstreamResponseJSONNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldUpstreamResponseJSON))
}

// ResultURLEQ applies the EQ predicate on the "result_url" field.
func ResultURLEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldResultURL, v))
}

// ResultURLNEQ applies the NEQ predicate on the "result_url" field.
func ResultURLNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldResultURL, v))
}

// ResultURLIn applies the In predicate on the "result_url" field.
func ResultURLIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldResultURL, vs...))
}

// ResultURLNotIn applies the NotIn predicate on the "result_url" field.
func ResultURLNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldResultURL, vs...))
}

// ResultURLGT applies the GT predicate on the "result_url" field.
func ResultURLGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldResultURL, v))
}

// ResultURLGTE applies the GTE predicate on the "result_url" field.
func ResultURLGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldResultURL, v))
}

// ResultURLLT applies the LT predicate on the "result_url" field.
func ResultURLLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldResultURL, v))
}

// ResultURLLTE applies the LTE predicate on the "result_url" field.
func ResultURLLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldResultURL, v))
}

// ResultURLContains applies the Contains predicate on the "result_url" field.
func ResultURLContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldResultURL, v))
}

// ResultURLHasPrefix applies the HasPrefix predicate on the "result_url" field.
func ResultURLHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldResultURL, v))
}

// ResultURLHasSuffix applies the HasSuffix predicate on the "result_url" field.
func ResultURLHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldResultURL, v))
}

// ResultURLIsNil applies the IsNil predicate on the "result_url" field.
func ResultURLIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldResultURL))
}

// ResultURLNotNil applies the NotNil predicate on the "result_url" field.
func ResultURLNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldResultURL))
}

// ResultURLEqualFold applies the EqualFold predicate on the "result_url" field.
func ResultURLEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldResultURL, v))
}

// ResultURLContainsFold applies the ContainsFold predicate on the "result_url" field.
func ResultURLContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldResultURL, v))
}

// ResultContentTypeEQ applies the EQ predicate on the "result_content_type" field.
func ResultContentTypeEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldResultContentType, v))
}

// ResultContentTypeNEQ applies the NEQ predicate on the "result_content_type" field.
func ResultContentTypeNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldResultContentType, v))
}

// ResultContentTypeIn applies the In predicate on the "result_content_type" field.
func ResultContentTypeIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldResultContentType, vs...))
}

// ResultContentTypeNotIn applies the NotIn predicate on the "result_content_type" field.
func ResultContentTypeNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldResultContentType, vs...))
}

// ResultContentTypeGT applies the GT predicate on the "result_content_type" field.
func ResultContentTypeGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldResultContentType, v))
}

// ResultContentTypeGTE applies the GTE predicate on the "result_content_type" field.
func ResultContentTypeGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldResultContentType, v))
}

// ResultContentTypeLT applies the LT predicate on the "result_content_type" field.
func ResultContentTypeLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldResultContentType, v))
}

// ResultContentTypeLTE applies the LTE predicate on the "result_content_type" field.
func ResultContentTypeLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldResultContentType, v))
}

// ResultContentTypeContains applies the Contains predicate on the "result_content_type" field.
func ResultContentTypeContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldResultContentType, v))
}

// ResultContentTypeHasPrefix applies the HasPrefix predicate on the "result_content_type" field.
func ResultContentTypeHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldResultContentType, v))
}

// ResultContentTypeHasSuffix applies the HasSuffix predicate on the "result_content_type" field.
func ResultContentTypeHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldResultContentType, v))
}

// ResultContentTypeIsNil applies the IsNil predicate on the "result_content_type" field.
func ResultContentTypeIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldResultContentType))
}

// ResultContentTypeNotNil applies the NotNil predicate on the "result_content_type" field.
func ResultContentTypeNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldResultContentType))
}

// ResultContentTypeEqualFold applies the EqualFold predicate on the "result_content_type" field.
func ResultContentTypeEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldResultContentType, v))
}

// ResultContentTypeContainsFold applies the ContainsFold predicate on the "result_content_type" field.
func ResultContentTypeContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldResultContentType, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldExpiresAt))
}

// AudioVoiceEQ applies the EQ predicate on the "audio_voice" field.
func AudioVoiceEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioVoice, v))
}

// AudioVoiceNEQ applies the NEQ predicate on the "audio_voice" field.
func AudioVoiceNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldAudioVoice, v))
}

// AudioVoiceIn applies the In predicate on the "audio_voice" field.
func AudioVoiceIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldAudioVoice, vs...))
}

// AudioVoiceNotIn applies the NotIn predicate on the "audio_voice" field.
func AudioVoiceNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldAudioVoice, vs...))
}

// AudioVoiceGT applies the GT predicate on the "audio_voice" field.
func AudioVoiceGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldAudioVoice, v))
}

// AudioVoiceGTE applies the GTE predicate on the "audio_voice" field.
func AudioVoiceGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldAudioVoice, v))
}

// AudioVoiceLT applies the LT predicate on the "audio_voice" field.
func AudioVoiceLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldAudioVoice, v))
}

// AudioVoiceLTE applies the LTE predicate on the "audio_voice" field.
func AudioVoiceLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldAudioVoice, v))
}

// AudioVoiceContains applies the Contains predicate on the "audio_voice" field.
func AudioVoiceContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldAudioVoice, v))
}

// AudioVoiceHasPrefix applies the HasPrefix predicate on the "audio_voice" field.
func AudioVoiceHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldAudioVoice, v))
}

// AudioVoiceHasSuffix applies the HasSuffix predicate on the "audio_voice" field.
func AudioVoiceHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldAudioVoice, v))
}

// AudioVoiceIsNil applies the IsNil predicate on the "audio_voice" field.
func AudioVoiceIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldAudioVoice))
}

// AudioVoiceNotNil applies the NotNil predicate on the "audio_voice" field.
func AudioVoiceNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldAudioVoice))
}

// AudioVoiceEqualFold applies the EqualFold predicate on the "audio_voice" field.
func AudioVoiceEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldAudioVoice, v))
}

// AudioVoiceContainsFold applies the ContainsFold predicate on the "audio_voice" field.
func AudioVoiceContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldAudioVoice, v))
}

// AudioFormatEQ applies the EQ predicate on the "audio_format" field.
func AudioFormatEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioFormat, v))
}

// AudioFormatNEQ applies the NEQ predicate on the "audio_format" field.
func AudioFormatNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldAudioFormat, v))
}

// AudioFormatIn applies the In predicate on the "audio_format" field.
func AudioFormatIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldAudioFormat, vs...))
}

// AudioFormatNotIn applies the NotIn predicate on the "audio_format" field.
func AudioFormatNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldAudioFormat, vs...))
}

// AudioFormatGT applies the GT predicate on the "audio_format" field.
func AudioFormatGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldAudioFormat, v))
}

// AudioFormatGTE applies the GTE predicate on the "audio_format" field.
func AudioFormatGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldAudioFormat, v))
}

// AudioFormatLT applies the LT predicate on the "audio_format" field.
func AudioFormatLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldAudioFormat, v))
}

// AudioFormatLTE applies the LTE predicate on the "audio_format" field.
func AudioFormatLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldAudioFormat, v))
}

// AudioFormatContains applies the Contains predicate on the "audio_format" field.
func AudioFormatContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldAudioFormat, v))
}

// AudioFormatHasPrefix applies the HasPrefix predicate on the "audio_format" field.
func AudioFormatHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldAudioFormat, v))
}

// AudioFormatHasSuffix applies the HasSuffix predicate on the "audio_format" field.
func AudioFormatHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldAudioFormat, v))
}

// AudioFormatIsNil applies the IsNil predicate on the "audio_format" field.
func AudioFormatIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldAudioFormat))
}

// AudioFormatNotNil applies the NotNil predicate on the "audio_format" field.
func AudioFormatNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldAudioFormat))
}

// AudioFormatEqualFold applies the EqualFold predicate on the "audio_format" field.
func AudioFormatEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldAudioFormat, v))
}

// AudioFormatContainsFold applies the ContainsFold predicate on the "audio_format" field.
func AudioFormatContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldAudioFormat, v))
}

// AudioCharacterCountEQ applies the EQ predicate on the "audio_character_count" field.
func AudioCharacterCountEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldAudioCharacterCount, v))
}

// AudioCharacterCountNEQ applies the NEQ predicate on the "audio_character_count" field.
func AudioCharacterCountNEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldAudioCharacterCount, v))
}

// AudioCharacterCountIn applies the In predicate on the "audio_character_count" field.
func AudioCharacterCountIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldAudioCharacterCount, vs...))
}

// AudioCharacterCountNotIn applies the NotIn predicate on the "audio_character_count" field.
func AudioCharacterCountNotIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldAudioCharacterCount, vs...))
}

// AudioCharacterCountGT applies the GT predicate on the "audio_character_count" field.
func AudioCharacterCountGT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldAudioCharacterCount, v))
}

// AudioCharacterCountGTE applies the GTE predicate on the "audio_character_count" field.
func AudioCharacterCountGTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldAudioCharacterCount, v))
}

// AudioCharacterCountLT applies the LT predicate on the "audio_character_count" field.
func AudioCharacterCountLT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldAudioCharacterCount, v))
}

// AudioCharacterCountLTE applies the LTE predicate on the "audio_character_count" field.
func AudioCharacterCountLTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldAudioCharacterCount, v))
}

// VideoDurationSecondsEQ applies the EQ predicate on the "video_duration_seconds" field.
func VideoDurationSecondsEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsNEQ applies the NEQ predicate on the "video_duration_seconds" field.
func VideoDurationSecondsNEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsIn applies the In predicate on the "video_duration_seconds" field.
func VideoDurationSecondsIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldVideoDurationSeconds, vs...))
}

// VideoDurationSecondsNotIn applies the NotIn predicate on the "video_duration_seconds" field.
func VideoDurationSecondsNotIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldVideoDurationSeconds, vs...))
}

// VideoDurationSecondsGT applies the GT predicate on the "video_duration_seconds" field.
func VideoDurationSecondsGT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsGTE applies the GTE predicate on the "video_duration_seconds" field.
func VideoDurationSecondsGTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsLT applies the LT predicate on the "video_duration_seconds" field.
func VideoDurationSecondsLT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldVideoDurationSeconds, v))
}

// VideoDurationSecondsLTE applies the LTE predicate on the "video_duration_seconds" field.
func VideoDurationSecondsLTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldVideoDurationSeconds, v))
}

// VideoResolutionEQ applies the EQ predicate on the "video_resolution" field.
func VideoResolutionEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoResolution, v))
}

// VideoResolutionNEQ applies the NEQ predicate on the "video_resolution" field.
func VideoResolutionNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldVideoResolution, v))
}

// VideoResolutionIn applies the In predicate on the "video_resolution" field.
func VideoResolutionIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldVideoResolution, vs...))
}

// VideoResolutionNotIn applies the NotIn predicate on the "video_resolution" field.
func VideoResolutionNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldVideoResolution, vs...))
}

// VideoResolutionGT applies the GT predicate on the "video_resolution" field.
func VideoResolutionGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldVideoResolution, v))
}

// VideoResolutionGTE applies the GTE predicate on the "video_resolution" field.
func VideoResolutionGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldVideoResolution, v))
}

// VideoResolutionLT applies the LT predicate on the "video_resolution" field.
func VideoResolutionLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldVideoResolution, v))
}

// VideoResolutionLTE applies the LTE predicate on the "video_resolution" field.
func VideoResolutionLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldVideoResolution, v))
}

// VideoResolutionContains applies the Contains predicate on the "video_resolution" field.
func VideoResolutionContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldVideoResolution, v))
}

// VideoResolutionHasPrefix applies the HasPrefix predicate on the "video_resolution" field.
func VideoResolutionHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldVideoResolution, v))
}

// VideoResolutionHasSuffix applies the HasSuffix predicate on the "video_resolution" field.
func VideoResolutionHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldVideoResolution, v))
}

// VideoResolutionIsNil applies the IsNil predicate on the "video_resolution" field.
func VideoResolutionIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldVideoResolution))
}

// VideoResolutionNotNil applies the NotNil predicate on the "video_resolution" field.
func VideoResolutionNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldVideoResolution))
}

// VideoResolutionEqualFold applies the EqualFold predicate on the "video_resolution" field.
func VideoResolutionEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldVideoResolution, v))
}

// VideoResolutionContainsFold applies the ContainsFold predicate on the "video_resolution" field.
func VideoResolutionContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldVideoResolution, v))
}

// VideoRatioEQ applies the EQ predicate on the "video_ratio" field.
func VideoRatioEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoRatio, v))
}

// VideoRatioNEQ applies the NEQ predicate on the "video_ratio" field.
func VideoRatioNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldVideoRatio, v))
}

// VideoRatioIn applies the In predicate on the "video_ratio" field.
func VideoRatioIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldVideoRatio, vs...))
}

// VideoRatioNotIn applies the NotIn predicate on the "video_ratio" field.
func VideoRatioNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldVideoRatio, vs...))
}

// VideoRatioGT applies the GT predicate on the "video_ratio" field.
func VideoRatioGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldVideoRatio, v))
}

// VideoRatioGTE applies the GTE predicate on the "video_ratio" field.
func VideoRatioGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldVideoRatio, v))
}

// VideoRatioLT applies the LT predicate on the "video_ratio" field.
func VideoRatioLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldVideoRatio, v))
}

// VideoRatioLTE applies the LTE predicate on the "video_ratio" field.
func VideoRatioLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldVideoRatio, v))
}

// VideoRatioContains applies the Contains predicate on the "video_ratio" field.
func VideoRatioContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldVideoRatio, v))
}

// VideoRatioHasPrefix applies the HasPrefix predicate on the "video_ratio" field.
func VideoRatioHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldVideoRatio, v))
}

// VideoRatioHasSuffix applies the HasSuffix predicate on the "video_ratio" field.
func VideoRatioHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldVideoRatio, v))
}

// VideoRatioIsNil applies the IsNil predicate on the "video_ratio" field.
func VideoRatioIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldVideoRatio))
}

// VideoRatioNotNil applies the NotNil predicate on the "video_ratio" field.
func VideoRatioNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldVideoRatio))
}

// VideoRatioEqualFold applies the EqualFold predicate on the "video_ratio" field.
func VideoRatioEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldVideoRatio, v))
}

// VideoRatioContainsFold applies the ContainsFold predicate on the "video_ratio" field.
func VideoRatioContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldVideoRatio, v))
}

// VideoCountEQ applies the EQ predicate on the "video_count" field.
func VideoCountEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldVideoCount, v))
}

// VideoCountNEQ applies the NEQ predicate on the "video_count" field.
func VideoCountNEQ(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldVideoCount, v))
}

// VideoCountIn applies the In predicate on the "video_count" field.
func VideoCountIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldVideoCount, vs...))
}

// VideoCountNotIn applies the NotIn predicate on the "video_count" field.
func VideoCountNotIn(vs ...int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldVideoCount, vs...))
}

// VideoCountGT applies the GT predicate on the "video_count" field.
func VideoCountGT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldVideoCount, v))
}

// VideoCountGTE applies the GTE predicate on the "video_count" field.
func VideoCountGTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldVideoCount, v))
}

// VideoCountLT applies the LT predicate on the "video_count" field.
func VideoCountLT(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldVideoCount, v))
}

// VideoCountLTE applies the LTE predicate on the "video_count" field.
func VideoCountLTE(v int) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldVideoCount, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// UsageRecordedAtEQ applies the EQ predicate on the "usage_recorded_at" field.
func UsageRecordedAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldUsageRecordedAt, v))
}

// UsageRecordedAtNEQ applies the NEQ predicate on the "usage_recorded_at" field.
func UsageRecordedAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldUsageRecordedAt, v))
}

// UsageRecordedAtIn applies the In predicate on the "usage_recorded_at" field.
func UsageRecordedAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldUsageRecordedAt, vs...))
}

// UsageRecordedAtNotIn applies the NotIn predicate on the "usage_recorded_at" field.
func UsageRecordedAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldUsageRecordedAt, vs...))
}

// UsageRecordedAtGT applies the GT predicate on the "usage_recorded_at" field.
func UsageRecordedAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldUsageRecordedAt, v))
}

// UsageRecordedAtGTE applies the GTE predicate on the "usage_recorded_at" field.
func UsageRecordedAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldUsageRecordedAt, v))
}

// UsageRecordedAtLT applies the LT predicate on the "usage_recorded_at" field.
func UsageRecordedAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldUsageRecordedAt, v))
}

// UsageRecordedAtLTE applies the LTE predicate on the "usage_recorded_at" field.
func UsageRecordedAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldUsageRecordedAt, v))
}

// UsageRecordedAtIsNil applies the IsNil predicate on the "usage_recorded_at" field.
func UsageRecordedAtIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldUsageRecordedAt))
}

// UsageRecordedAtNotNil applies the NotNil predicate on the "usage_recorded_at" field.
func UsageRecordedAtNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldUsageRecordedAt))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldSubmittedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaGenerationJob) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaGenerationJob) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaGenerationJob) predicate.MediaGenerationJob {
	return predicate.MediaGenerationJob(sql.NotPredicates(p))
}
